version: 2

defaults: &defaults
    parallelism: 4
    working_directory: ~/zoomhub/zoomhub
    environment:
        CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
        CIRCLE_TEST_REPORTS: /tmp/circleci-test-results

deploy: &deploy
    docker:
        - image: buildpack-deps:trusty
    steps:
      - attach_workspace:
          at: ~/zoomhub/zoomhub/workspace
      - run:
          name: SSH setup
          command: mkdir -p ~/.ssh && ssh-keyscan "$DEPLOY_HOST" >> ~/.ssh/known_hosts
      - run:
          name: Deploy
          command: cd ~/zoomhub/zoomhub/workspace && ./deploy.sh "$DEPLOY_HOST"

jobs:
  build:
    <<: *defaults
    docker:
      - image: fpco/stack-build
    steps:
    - checkout

    - run:
        name: Initialize workspace
        command: mkdir -p workspace
    - run:
        name: Initialize artifact storage
        command: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - run: sudo apt-get update
    - run:
        name: Install pgloader
        command: sudo apt-get install --yes pgloader
    - run:
        name: Build and install plv8 PostgreSQL extension
        command: |
          sudo apt-get update
          sudo pip install pgxnclient
          sudo apt-get install --yes libpq-dev libv8-dev postgresql-server-dev-9.5
          sudo pgxn install 'plv8=1.4.4'
          sudo service postgresql stop 9.4
          sudo service postgresql restart 9.5

    # Dependencies
    #   This would typically go in either a build or a build-and-test job when
    #   using workflows
    # Restore the dependency cache
    - restore_cache:
        keys:
        - zh-stack-cache-v1-dep-{{ .Branch }}-{{ checksum "zoomhub.cabal" }}
        # This branch if available
        - zh-stack-cache-v1-dep-{{ .Branch }}-
        # Default branch if not
        - zh-stack-cache-v1-dep-master-
        # Any branch if there are none on the default branch -
        # this should be unnecessary if you have your default branch
        # configured correctly
        - zh-stack-cache-v1-dep-
    - run:
        name: Build binary
        command: stack build --install-ghc --pedantic --ghc-options="-O2"
    - run:
        name: Create Keter package
        command: ./ops/keter-bundle.sh
    - run:
        name: Copy Keter package to artifacts
        command: cp zoomhub.keter $CIRCLE_ARTIFACTS
    - run:
        name: Copy Keter package to workspace
        command: cp zoomhub.keter workspace
    - run:
        name: Copy deploy script to workspace
        command: cp ./ops/deploy.sh workspace

    - persist_to_workspace:
        root: workspace
        paths:
          - zoomhub.keter
          - deploy.sh

    # Save dependency cache
    - save_cache:
        key: zh-stack-cache-v1-dep-{{ .Branch }}-{{ checksum "zoomhub.cabal" }}
        paths:
        - ~/.stack
        - .stack-work

    # Test
    - run:
        name: Prepare database for test
        command: pgloader ./data/zoomhub-development.sqlite3 postgresql://circleci-db-user@localhost:5432/circleci-test-db
    - run:
        name: Run tests
        command: PGUSER='circleci-db-user' PGDATABASE='circleci-test-db' stack test --no-terminal --coverage
    - run:
        name: Copy coverage reports
        command: cp -r $(stack path --local-hpc-root) $CIRCLE_ARTIFACTS

    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results

    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results

  deploy-staging:
    <<: *defaults
    environment:
        DEPLOY_HOST: staging.zoomhub.net
    <<: *deploy

  deploy-production:
    <<: *defaults
    environment:
        DEPLOY_HOST: zoomhub.net
    <<: *deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master
      - deploy-production:
          requires:
            - build
          filters:
            branches:
              only: master
