---
service: zoomhub
description: Cloud zooming service.
admin_user: zoomhub
admin_home: "/home/{{ admin_user }}"
admin_group: zoomhub
apps_root: /var/apps
app_repo: https://github.com/zoomhub/zoomhub.git
app_root: '{{ apps_root }}/{{ service }}'
app_version: master
app_environment: production
new_relic_app_name: '{{ service }}-{{ app_environment }}'
app_port: 3000
app_env:
  - NODE_ENV=production
  - PORT={{ app_port }}
  - BASE_URL='http://zoomhub.net'
  - DATA_DIR=/var/data/zoomhub
  - HOME={{ admin_home }}
  - CONTENT_DZIS_PREFIX=dzis/
  - EXPRESS_LOGGER_FORMAT=default
  - NEW_RELIC_APP_NAME={{ new_relic_app_name }}
  - NEW_RELIC_LICENSE_KEY={{ newrelic_key }}
  - NEW_RELIC_NO_CONFIG_FILE=true
  # TODO figure out a permanent location for the newrelic log
  - NEW_RELIC_LOG=/home/zoomhub/newrelic.log
  - RACKSPACE_API_KEY={{ rackspace_api_key }}
app_command: "{{ app_root }}/node_modules/.bin/_coffee --cache {{ app_root }}/app"
log_root: '/var/log/{{ service }}'
log_path: '/var/log/{{ service }}/{{ service }}.log'
