---
service: zoomhub
description: Cloud zooming service.
admin_user: zoomhub
admin_home: "/home/{{ admin_user }}"
admin_group: zoomhub
apps_root: /var/apps
app_repo: https://github.com/zoomhub/zoomhub.git
app_root: '{{ apps_root }}/{{ service }}'
app_version: master
app_port: 3000
app_env:
  - NODE_ENV=production
  - PORT={{ app_port }}
  - BASE_URL='http://zoomhub.net'
  - HOME={{ admin_home }}
app_command: "{{ app_root }}/node_modules/.bin/_coffee --fibers --cache {{ app_root }}/app"
log_root: '/var/log/{{ service }}'
log_path: '/var/log/{{ service }}/{{ service }}.log'
