---
- name: Install fail2ban
  apt: pkg=fail2ban state=installed

- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: restart ssh

- name: Disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin no"
              state=present
  notify: restart ssh

- name: Delete /etc/sudoers.d/ files
  shell: rm -f /etc/sudoers.d/*

- name: Install ufw (Uncomplicated Firewall)
  apt: pkg=ufw state=installed

- name: Setup ufw 22/tcp
  shell: ufw allow 22/tcp

- name: Setup ufw 80/tcp
  shell: ufw allow 80/tcp

- name: Setup ufw 443/tcp
  shell: ufw allow 443/tcp

- name: Enable ufw
  shell: echo 'y' | ufw enable

- name: Delete root password
  shell: passwd -d root
